apiVersion: v1
kind: Pod
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  containers:
    - name: testapp
      image: ht5767751012/java-related: js-01
      args:
        - "-http=0.0.0.0:80"
        - "-health=0.0.0.0:81"
        - "-secret=secret"
      ports:
        - name: http
          containerPort: 80
        - name: health
          containerPort: 81
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
          